spring:
  profiles:
    active: test


---
server:
  port: 9090

spring:
  profiles: test
  application:
    name: 9090test

---
server:
     port: 9091

spring:
  profiles: dev
  application:
    name: 9091test
