spring:
  profiles:
    active: test

---


server:
  port: 8085

spring:
  profiles:
    application: dev
      name: test-cloud.1


---

server:
  port: 8086

spring:
  profiles:
    application: test
      name: test-cloud.2
